name: 'Get inputs'
description: 'Get the dependencies and cache them'
inputs:
  if-cache: 
    description: 'Decide whether to cache or no'
    required: false #Set to true if always needed
    default: 'true'
runs:
  using: composite
  steps:
    - name: cache dependencies
      if: inputs.if-cache == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-with-input-${{ hashFiles('**/requirements.txt') }}
    - name: install packages
      if: steps.cache.outputs.cache-hit != 'true' || inputs.if-cache != 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt