name: 'Get cached dependencies'
description: 'Get the dependencies and cache them'
runs:
  using: composite
  steps:
    - name: cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: install packages
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt