name: use actions
on:
    push:
        branches:
          - main 
run-name: using composite actions 
jobs:
  use-composite-actions:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v4
        - name: load and cache dependencies
          id: cache-step
          uses: ./.github/actions/actions-with-output # Path from root folder of the project
          with:
            if-cache: 'false'
        - name: Output action
          run: echo "cache used ${{ steps.cache-step.outputs.if-cache-uses }}"

